# Generated by Django 3.1.2 on 2020-12-07 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201208_0030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commentstwo',
        ),
    ]
