# Generated by Django 3.1.2 on 2020-12-07 20:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_commentstwo'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
