# Generated by Django 3.1.2 on 2021-04-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='location',
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(default='other', max_length=30),
        ),
    ]
