# Generated by Django 3.1.2 on 2021-04-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210413_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(choices=[('news', 'NEWS'), ('politics', 'POLITICS'), ('entertainment', 'ENTERTAINMENT'), ('travel', 'TRAVEL'), ('food', 'FOOD'), ('other', 'OTHER')], default='other', max_length=30),
        ),
    ]
