# Generated by Django 3.1.2 on 2021-04-13 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='example',
        ),
    ]
