# Generated by Django 3.1.2 on 2021-04-13 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_delete_example'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
