# Generated by Django 3.1.2 on 2021-04-14 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
