# Generated by Django 3.1.2 on 2021-04-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20210416_1230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New',
        ),
        migrations.AddField(
            model_name='post',
            name='example',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='blogimage',
            field=models.ImageField(default='blog.jpg', upload_to='media'),
        ),
    ]
