# Generated by Django 3.1.2 on 2021-04-16 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20210416_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='example',
        ),
    ]
