# Generated by Django 3.1.2 on 2020-12-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0002_userdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='Continent',
            new_name='continent',
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='Country',
            new_name='country',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
