# Generated by Django 3.1.2 on 2020-12-03 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0004_userdetailstwo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetailstwo',
            old_name='user',
            new_name='jaga',
        ),
    ]
