# Generated by Django 3.1.2 on 2020-12-03 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0006_auto_20201203_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetailstwo',
            name='user',
        ),
    ]
