# Generated by Django 3.1.2 on 2021-04-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0007_remove_userdetailstwo_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetailstwo',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='nickname',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
