# Generated by Django 3.1.2 on 2021-04-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0011_auto_20210412_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phonenumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileno', models.IntegerField()),
            ],
        ),
    ]
