# Generated by Django 3.1.2 on 2021-04-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0014_auto_20210413_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumbers',
            name='date',
        ),
        migrations.RemoveField(
            model_name='phonenumbers',
            name='month',
        ),
        migrations.RemoveField(
            model_name='phonenumbers',
            name='year',
        ),
        migrations.AddField(
            model_name='phonenumbers',
            name='birthday',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
