# Generated by Django 3.1.2 on 2021-04-14 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0016_profile_backimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='backimage',
            new_name='background_image',
        ),
    ]
