# Generated by Django 3.1.2 on 2021-04-16 08:10

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0019_remove_phonenumbers_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='dropcountry',
            field=django_countries.fields.CountryField(default='India', max_length=2),
        ),
    ]
