# Generated by Django 3.1.2 on 2021-04-17 13:51

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0020_auto_20210416_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='dropcountry',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
