# Generated by Django 3.1.2 on 2021-04-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0021_auto_20210417_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumbers',
            name='mobileno',
            field=models.BigIntegerField(),
        ),
    ]
